# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_object_configuration_python_sdk.pydantic.calculation_concept_configuration_dto import CalculationConceptConfigurationDTO

class CalculationConceptDTO(BaseModel):
    # The unique identifier associated with the calculation concept.
    uuid: typing.Optional[str] = Field(None, alias='uuid')

    # The display name of the calculation concept.
    name: typing.Optional[str] = Field(None, alias='name')

    # A list of objects representing the configuration for the calculation concept.
    configuration: typing.Optional[CalculationConceptConfigurationDTO] = Field(None, alias='configuration')
    class Config:
        arbitrary_types_allowed = True
