# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_object_configuration_python_sdk.pydantic.dimension_member_dto import DimensionMemberDTO

class DimensionFilterDTO(BaseModel):
    # The UUID of the dimension.
    dimension_id: typing.Optional[str] = Field(None, alias='dimensionId')

    # The symbol name of the dimension.
    symbol_name: typing.Optional[str] = Field(None, alias='symbolName')

    # A list of dimension members to map to the perspective node.   Note: If this array is empty, all dimension members will be removed for the node.
    dimension_members: typing.Optional[typing.List[DimensionMemberDTO]] = Field(None, alias='dimensionMembers')
    class Config:
        arbitrary_types_allowed = True
