# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_object_configuration_python_sdk.pydantic.analytic_object_filter_dto import AnalyticObjectFilterDTO

class SelectionConceptConfigurationMapDTO(BaseModel):
    # A list of analytic object filters indicating the analytic object and dimension members used  for the selection concept.   Note: If this array is empty, all filters will be removed for the concept.
    analytic_object_filters_to_map: typing.Optional[typing.List[AnalyticObjectFilterDTO]] = Field(None, alias='analyticObjectFiltersToMap')
    class Config:
        arbitrary_types_allowed = True
