# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_object_configuration_python_sdk import schemas  # noqa: F401


class AnalyticObjectFilterDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            analyticObjectUuid = schemas.StrSchema
            symbolName = schemas.StrSchema
            
            
            class dimensions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['DimensionFilterDTO']:
                        return DimensionFilterDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['DimensionFilterDTO'], typing.List['DimensionFilterDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'dimensions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'DimensionFilterDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "analyticObjectUuid": analyticObjectUuid,
                "symbolName": symbolName,
                "dimensions": dimensions,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["analyticObjectUuid"]) -> MetaOapg.properties.analyticObjectUuid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["symbolName"]) -> MetaOapg.properties.symbolName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dimensions"]) -> MetaOapg.properties.dimensions: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["analyticObjectUuid", "symbolName", "dimensions", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["analyticObjectUuid"]) -> typing.Union[MetaOapg.properties.analyticObjectUuid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["symbolName"]) -> typing.Union[MetaOapg.properties.symbolName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dimensions"]) -> typing.Union[MetaOapg.properties.dimensions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["analyticObjectUuid", "symbolName", "dimensions", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        analyticObjectUuid: typing.Union[MetaOapg.properties.analyticObjectUuid, str, schemas.Unset] = schemas.unset,
        symbolName: typing.Union[MetaOapg.properties.symbolName, str, schemas.Unset] = schemas.unset,
        dimensions: typing.Union[MetaOapg.properties.dimensions, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AnalyticObjectFilterDTO':
        return super().__new__(
            cls,
            *args,
            analyticObjectUuid=analyticObjectUuid,
            symbolName=symbolName,
            dimensions=dimensions,
            _configuration=_configuration,
            **kwargs,
        )

from visier_object_configuration_python_sdk.model.dimension_filter_dto import DimensionFilterDTO
