# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_object_configuration_python_sdk import schemas  # noqa: F401


class CalculationConceptConfigurationMapDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The configuration to apply to the concept.
    """


    class MetaOapg:
        
        class properties:
            
            
            class perspectivesToMap(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PerspectiveConfigurationDTO']:
                        return PerspectiveConfigurationDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['PerspectiveConfigurationDTO'], typing.List['PerspectiveConfigurationDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'perspectivesToMap':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PerspectiveConfigurationDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "perspectivesToMap": perspectivesToMap,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["perspectivesToMap"]) -> MetaOapg.properties.perspectivesToMap: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["perspectivesToMap", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["perspectivesToMap"]) -> typing.Union[MetaOapg.properties.perspectivesToMap, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["perspectivesToMap", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        perspectivesToMap: typing.Union[MetaOapg.properties.perspectivesToMap, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CalculationConceptConfigurationMapDTO':
        return super().__new__(
            cls,
            *args,
            perspectivesToMap=perspectivesToMap,
            _configuration=_configuration,
            **kwargs,
        )

from visier_object_configuration_python_sdk.model.perspective_configuration_dto import PerspectiveConfigurationDTO
