# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_object_configuration_python_sdk import schemas  # noqa: F401


class DimensionFilterDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            dimensionId = schemas.StrSchema
            symbolName = schemas.StrSchema
            
            
            class dimensionMembers(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['DimensionMemberDTO']:
                        return DimensionMemberDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['DimensionMemberDTO'], typing.List['DimensionMemberDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'dimensionMembers':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'DimensionMemberDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "dimensionId": dimensionId,
                "symbolName": symbolName,
                "dimensionMembers": dimensionMembers,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dimensionId"]) -> MetaOapg.properties.dimensionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["symbolName"]) -> MetaOapg.properties.symbolName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dimensionMembers"]) -> MetaOapg.properties.dimensionMembers: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["dimensionId", "symbolName", "dimensionMembers", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dimensionId"]) -> typing.Union[MetaOapg.properties.dimensionId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["symbolName"]) -> typing.Union[MetaOapg.properties.symbolName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dimensionMembers"]) -> typing.Union[MetaOapg.properties.dimensionMembers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["dimensionId", "symbolName", "dimensionMembers", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        dimensionId: typing.Union[MetaOapg.properties.dimensionId, str, schemas.Unset] = schemas.unset,
        symbolName: typing.Union[MetaOapg.properties.symbolName, str, schemas.Unset] = schemas.unset,
        dimensionMembers: typing.Union[MetaOapg.properties.dimensionMembers, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DimensionFilterDTO':
        return super().__new__(
            cls,
            *args,
            dimensionId=dimensionId,
            symbolName=symbolName,
            dimensionMembers=dimensionMembers,
            _configuration=_configuration,
            **kwargs,
        )

from visier_object_configuration_python_sdk.model.dimension_member_dto import DimensionMemberDTO
