# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_object_configuration_python_sdk
from visier_object_configuration_python_sdk.model.perspective_node_dto import PerspectiveNodeDTO
from visier_object_configuration_python_sdk import configuration


class TestPerspectiveNodeDTO(unittest.TestCase):
    """PerspectiveNodeDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
