# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_object_configuration_python_sdk
from visier_object_configuration_python_sdk.model.selection_concept_list_dto import SelectionConceptListDTO
from visier_object_configuration_python_sdk import configuration


class TestSelectionConceptListDTO(unittest.TestCase):
    """SelectionConceptListDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
