# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import visier_object_configuration_python_sdk
from visier_object_configuration_python_sdk.paths.v1_admin_calculation_concepts import get
from visier_object_configuration_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1AdminCalculationConcepts(ApiTestMixin, unittest.TestCase):
    """
    V1AdminCalculationConcepts unit test stubs
        Retrieve all calculation concepts
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
