# coding: utf-8
"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from visier_object_configuration_python_sdk.client_custom import ClientCustom
from visier_object_configuration_python_sdk.configuration import Configuration
from visier_object_configuration_python_sdk.api_client import ApiClient
from visier_object_configuration_python_sdk.type_util import copy_signature
from visier_object_configuration_python_sdk.apis.tags.object_configuration_api import ObjectConfigurationApi



class VisierObjectConfiguration(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.object_configuration: ObjectConfigurationApi = ObjectConfigurationApi(api_client)
