# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_object_configuration_python_sdk.paths.v1_admin_calculation_concepts_concept_id.get import GetCalculationConcept
from visier_object_configuration_python_sdk.paths.v1_admin_calculation_concepts.get import GetCalculationConcepts
from visier_object_configuration_python_sdk.paths.v1_admin_selection_concepts_concept_id.get import GetSelectionConcept
from visier_object_configuration_python_sdk.paths.v1_admin_selection_concepts.get import GetSelectionConcepts
from visier_object_configuration_python_sdk.paths.v1_admin_calculation_concepts_concept_id_configure.put import MapCalculationConcept
from visier_object_configuration_python_sdk.paths.v1_admin_selection_concepts_concept_id_configure.put import MapSelectionConcept
from visier_object_configuration_python_sdk.apis.tags.object_configuration_api_raw import ObjectConfigurationApiRaw


class ObjectConfigurationApi(
    GetCalculationConcept,
    GetCalculationConcepts,
    GetSelectionConcept,
    GetSelectionConcepts,
    MapCalculationConcept,
    MapSelectionConcept,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ObjectConfigurationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ObjectConfigurationApiRaw(api_client)
