# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_object_configuration_python_sdk.paths.v1_admin_calculation_concepts_concept_id.get import GetCalculationConceptRaw
from visier_object_configuration_python_sdk.paths.v1_admin_calculation_concepts.get import GetCalculationConceptsRaw
from visier_object_configuration_python_sdk.paths.v1_admin_selection_concepts_concept_id.get import GetSelectionConceptRaw
from visier_object_configuration_python_sdk.paths.v1_admin_selection_concepts.get import GetSelectionConceptsRaw
from visier_object_configuration_python_sdk.paths.v1_admin_calculation_concepts_concept_id_configure.put import MapCalculationConceptRaw
from visier_object_configuration_python_sdk.paths.v1_admin_selection_concepts_concept_id_configure.put import MapSelectionConceptRaw


class ObjectConfigurationApiRaw(
    GetCalculationConceptRaw,
    GetCalculationConceptsRaw,
    GetSelectionConceptRaw,
    GetSelectionConceptsRaw,
    MapCalculationConceptRaw,
    MapSelectionConceptRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
