# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_object_configuration_python_sdk.type.dimension_filter_dto import DimensionFilterDTO

class RequiredAnalyticObjectFilterDTO(TypedDict):
    pass

class OptionalAnalyticObjectFilterDTO(TypedDict, total=False):
    # The UUID of the analytic object used in the selection concept.
    analyticObjectUuid: str

    # The symbol name of the analytic object.
    symbolName: str

    # A list of dimensions included in the concept.
    dimensions: typing.List[DimensionFilterDTO]

class AnalyticObjectFilterDTO(RequiredAnalyticObjectFilterDTO, OptionalAnalyticObjectFilterDTO):
    pass
