# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_object_configuration_python_sdk.type.dimension_member_dto_dimension_member import DimensionMemberDTODimensionMember

class RequiredDimensionMemberDTO(TypedDict):
    pass

class OptionalDimensionMemberDTO(TypedDict, total=False):
    dimensionMember: DimensionMemberDTODimensionMember

class DimensionMemberDTO(RequiredDimensionMemberDTO, OptionalDimensionMemberDTO):
    pass
