# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_object_configuration_python_sdk.type.dimension_member_dto import DimensionMemberDTO

class RequiredDimensionFilterDTO(TypedDict):
    pass

class OptionalDimensionFilterDTO(TypedDict, total=False):
    # The UUID of the dimension.
    dimensionId: str

    # The symbol name of the dimension.
    symbolName: str

    # A list of dimension members to map to the perspective node.   Note: If this array is empty, all dimension members will be removed for the node.
    dimensionMembers: typing.List[DimensionMemberDTO]

class DimensionFilterDTO(RequiredDimensionFilterDTO, OptionalDimensionFilterDTO):
    pass
