# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_object_configuration_python_sdk.type.analytic_object_filter_dto import AnalyticObjectFilterDTO

class RequiredPerspectiveNodeDTO(TypedDict):
    pass

class OptionalPerspectiveNodeDTO(TypedDict, total=False):
    # The UUID of the node's selection concept. Perspective nodes are generated as selection concepts to enable filtering.
    selectionConceptUuid: str

    # The symbol name of the selection concept. For example, \"isExitActualSystemTermination\".
    symbolName: str

    # A list of analytic object filters indicating the analytic object and dimensions used for the selection concept.
    analyticObjectFilters: typing.List[AnalyticObjectFilterDTO]

class PerspectiveNodeDTO(RequiredPerspectiveNodeDTO, OptionalPerspectiveNodeDTO):
    pass
