# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_object_configuration_python_sdk.type.perspective_node_dto import PerspectiveNodeDTO

class RequiredPerspectiveConfigurationDTO(TypedDict):
    pass

class OptionalPerspectiveConfigurationDTO(TypedDict, total=False):
    # The UUID of the perspective.
    perspectiveId: str

    # The display name of the perspective.
    perspectiveName: str

    # A list of nodes in the perspective.
    perspectiveNodes: typing.List[PerspectiveNodeDTO]

class PerspectiveConfigurationDTO(RequiredPerspectiveConfigurationDTO, OptionalPerspectiveConfigurationDTO):
    pass
