# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_object_configuration_python_sdk.type.selection_concept_dto import SelectionConceptDTO

class RequiredSelectionConceptListDTO(TypedDict):
    pass

class OptionalSelectionConceptListDTO(TypedDict, total=False):
    # A list of objects representing selection concepts.
    concepts: typing.List[SelectionConceptDTO]

class SelectionConceptListDTO(RequiredSelectionConceptListDTO, OptionalSelectionConceptListDTO):
    pass
