# coding: utf-8

"""
    Visier Object Configuration APIs

    Visier APIs for managing objects in studio experience

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_object_configuration_python_sdk.type.selection_concept_configuration_dto import SelectionConceptConfigurationDTO

class RequiredSelectionConceptDTO(TypedDict):
    pass

class OptionalSelectionConceptDTO(TypedDict, total=False):
    # The unique identifier associated with the selection concept.
    uuid: str

    # The display name of the selection concept.
    name: str

    # A list of objects representing the configuration for the selection concept.
    configuration: SelectionConceptConfigurationDTO

class SelectionConceptDTO(RequiredSelectionConceptDTO, OptionalSelectionConceptDTO):
    pass
